
'''
Bob Schiffrin November 2021

This script colours models of proteins and protein complexes generated by AlphaFold 
according to their per residue Predicted Local Distance Difference Test scores (pLDDTs).
The colouring uses the values stored in b factor column of the model pdb file and 
colours them according to the colour scheme used in the AlphaFold/EBI protein structure
database (https://alphafold.ebi.ac.uk/):

    Very high (pLDDT > 90)
    Confident (90 > pLDDT > 70)
    Low (70 > pLDDT > 50)
    Very low (pLDDT < 50)


To use, at the PyMOL prompt enter:

run colour_af_plddt.py

'''

def colour_af_plddt(selection="all"):
    
    blue_rgb = [0,76,202]
    blue = []
    for c in blue_rgb:
        blue.append(c/255.0)

    lightblue_rgb = [73, 196, 238]
    lightblue = []
    for c in lightblue_rgb:
        lightblue.append(c/255.0)

    yellow_rgb = [255, 213, 57]
    yellow = []
    for c in yellow_rgb:
        yellow.append(c/255.0)

    orange_rgb = [255, 113, 67]
    orange = []
    for c in orange_rgb:
        orange.append(c/255.0)
        
    
    #select and colour blue
    blue_upper = 100.0
    blue_lower = 90.0

    blue_sel_str = selection + " & ! b < " + str(blue_lower) + " & ! b > " + str(blue_upper)
    cmd.select('very_high', blue_sel_str)
    cmd.set_color('blue_plddt', blue)
    cmd.color('blue_plddt', 'very_high')

    #select and colour lightblue
    lightblue_upper = 90.0
    lightblue_lower = 70.0

    lightblue_sel_str = selection + " & ! b < " + str(lightblue_lower) + " & ! b > " + str(lightblue_upper)
    cmd.select('confident', lightblue_sel_str)
    cmd.set_color('lightblue_plddt', lightblue)
    cmd.color('lightblue_plddt', 'confident')

    #select and colour yellow
    yellow_upper = 70.0
    yellow_lower = 50.0

    yellow_sel_str = selection + " & ! b < " + str(yellow_lower) + " & ! b > " + str(yellow_upper)
    cmd.select('low', yellow_sel_str)
    cmd.set_color('yellow_plddt', yellow)
    cmd.color('yellow_plddt', 'low')

    #select and colour orange
    orange_upper = 50.0
    orange_lower = 0.0

    orange_sel_str = selection + " & ! b < " + str(orange_lower) + " & ! b > " + str(orange_upper)
    cmd.select('very_low', orange_sel_str)
    cmd.set_color('orange_plddt', orange)
    cmd.color('orange_plddt', 'very_low')

    cmd.deselect()


cmd.extend("colour_af_plddt", colour_af_plddt)
colour_af_plddt()


